url: 'https://beyondprototyping.github.io' #'https://beyond.prototyping.id' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: 'WorkshopWeb2023' # the subpath of your site, e.g. /blog
title: 'Beyond Prototyping' # the name of your site, e.g. ACME Corp.
repository: BeyondPrototyping/WorkshopWeb2023

collections:
  organizers:
    output: true
  papers:
    output: true

defaults:
  - scope:
      path: ''
      type: 'organizers'
    values:
      layout: 'organizer'
  - scope:
      path: ''
    values:
      layout: 'default'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
