url: "https://mannulambrichts.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ElectroFabWorkshop" # the subpath of your site, e.g. /blog
title: "ElectroFab" # the name of your site, e.g. ACME Corp.


collections:
  organizers:
    output: true

defaults:
  - scope:
      path: ""
      type: "organizers"
    values:
      layout: "organizer"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag